# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://sicearpenteurs.com
title: Sicé Arpenteurs-Géomètres
email: sice@sicearpenteurs.com
author: Yves Sicé
description: Le document requis dans une transaction immobilière est le certificat de localisation. Ce document doit être fourni par l'arpenteur-géomètre.Sur la Rive-Sud et ailleurs, nous en avons préparé plus de 13000 depuis 53 ans. Notre étude offre également toute une gamme de services d’arpentage allant de la pose de bornes à l’expertise.
copyright: 'Copyright &copy; 2017 Gabriel Bédard Sicé. All Rights Reserved.'
credits: 'Credits: <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Courriel
    icon: envelope
    url: "mailto:sice@sicearpenteurs.com"
    target: _blank
